INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (1,"AFG","Afghanistan","Kabul", 2, 652230); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (2,"ALB","Albania","Tirana", 3, 28748); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (3,"DZA","Algeria","Algiers", 1, 2381741); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (4,"ASM","American Samoa","Pago Pago", 5, 199); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (5,"AND","Andorra","Andorra la Vella", 3, 468); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (6,"AGO","Angola","Luanda", 1, 1246700); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (7,"AIA","Anguilla","The Valley", 4, 91); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (8,"ATG","Antigua and Barbuda","Saint John’s", 4, 442); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (9,"ARG","Argentina","Buenos Aires", 6, 2780400); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (10,"ARM","Armenia","Yerevan", 2, 29743); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (11,"ABW","Aruba","Oranjestad", 4, 180); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (12,"AUS","Australia","Canberra", 5, 7692024); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (13,"AUT","Austria","Vienna", 3, 83871); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (14,"AZE","Azerbaijan","Baku", 2, 86600); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (15,"BHS","Bahamas","Nassau", 4, 13943); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (16,"BHR","Bahrain","Manama", 2, 765); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (17,"BGD","Bangladesh","Dhaka", 2, 147570); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (18,"BRB","Barbados","Bridgetown", 4, 430); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (19,"BLR","Belarus","Minsk", 3, 207600); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (20,"BEL","Belgium","Brussels", 3, 30528); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (21,"BLZ","Belize","Belmopan", 4, 22966); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (22,"BEN","Benin","Porto-Novo", 1, 112622); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (23,"BMU","Bermuda","Hamilton", 4, 54); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (24,"BTN","Bhutan","Thimphu", 2, 38394); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (25,"BOL","Bolivia","Sucre", 6, 1098581); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (26,"BIH","Bosnia and Herzegovina","Sarajevo", 3, 51209); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (27,"BWA","Botswana","Gaborone", 1, 582000); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (28,"BRA","Brazil","Brasilia", 6, 8515767); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (29,"VGB","British Virgin Islands","Road Town", 4, 151); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (30,"BRN","Brunei","Bandar Seri Begawan", 2, 5765); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (31,"BGR","Bulgaria","Sofia", 3, 110879); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (32,"BFA","Burkina Faso","Ouagadougou", 1, 272967); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (33,"BDI","Burundi","Bujumbura", 1, 27834); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (34,"KHM","Cambodia","Phnom Penh", 2, 181035); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (35,"CMR","Cameroon","Yaounde", 1, 475442); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (36,"CAN","Canada","Ottawa", 4, 9984670); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (37,"CPV","Cape Verde","Praia", 1, 4033); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (38,"CYM","Cayman Islands","George Town", 4, 264); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (39,"CAF","Central African Republic","Bangui", 1, 622984); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (40,"TCD","Chad","N'Djamena", 1, 1284000); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (41,"CHL","Chile","Santiago", 6, 756102); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (42,"CHN","China","Beijing", 2, 9706961); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (43,"COL","Colombia","Bogota", 6, 1141748); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (44,"COM","Comoros","Moroni", 1, 1862); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (45,"COK","Cook Islands","Avarua", 5, 236); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (46,"CRI","Costa Rica","San José", 4, 51100); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (47,"HRV","Croatia","Zagreb", 3, 56594); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (48,"CUB","Cuba","Havana", 4, 109884); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (49,"CUW","Curacao","Willemstad", 4, 444); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (50,"CYP","Cyprus","Nicosia", 3, 9251); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (51,"CZE","Czech Republic","Prague", 3, 78865); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (52,"DNK","Denmark","Copenhagen", 3, 43094); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (53,"DJI","Djibouti","Djibouti", 1, 23200); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (54,"DMA","Dominica","Roseau", 4, 751); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (55,"DOM","Dominican Republic","Santo Domingo", 4, 48671); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (56,"COD","DR Congo","Kinshasa", 1, 2344858); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (57,"ECU","Ecuador","Quito", 6, 276841); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (58,"EGY","Egypt","Cairo", 1, 1002450); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (59,"SLV","El Salvador","San Salvador", 4, 21041); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (60,"GNQ","Equatorial Guinea","Malabo", 1, 28051); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (61,"ERI","Eritrea","Asmara", 1, 117600); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (62,"EST","Estonia","Tallinn", 3, 45227); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (63,"SWZ","Eswatini","Mbabane", 1, 17364); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (64,"ETH","Ethiopia","Addis Ababa", 1, 1104300); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (65,"FLK","Falkland Islands","Stanley", 6, 12173); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (66,"FRO","Faroe Islands","Tórshavn", 3, 1393); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (67,"FJI","Fiji","Suva", 5, 18272); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (68,"FIN","Finland","Helsinki", 3, 338424); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (69,"FRA","France","Paris", 3, 551695); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (70,"GUF","French Guiana","Cayenne", 6, 83534); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (71,"PYF","French Polynesia","Papeete", 5, 4167); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (72,"GAB","Gabon","Libreville", 1, 267668); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (73,"GMB","Gambia","Banjul", 1, 10689); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (74,"GEO","Georgia","Tbilisi", 2, 69700); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (75,"DEU","Germany","Berlin", 3, 357114); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (76,"GHA","Ghana","Accra", 1, 238533); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (77,"GIB","Gibraltar","Gibraltar", 3, 6); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (78,"GRC","Greece","Athens", 3, 131990); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (79,"GRL","Greenland","Nuuk", 4, 2166086); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (80,"GRD","Grenada","Saint George's", 4, 344); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (81,"GLP","Guadeloupe","Basse-Terre", 4, 1628); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (82,"GUM","Guam","Hagåtña", 5, 549); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (83,"GTM","Guatemala","Guatemala City", 4, 108889); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (84,"GGY","Guernsey","Saint Peter Port", 3, 78); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (85,"GIN","Guinea","Conakry", 1, 245857); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (86,"GNB","Guinea-Bissau","Bissau", 1, 36125); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (87,"GUY","Guyana","Georgetown", 6, 214969); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (88,"HTI","Haiti","Port-au-Prince", 4, 27750); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (89,"HND","Honduras","Tegucigalpa", 4, 112492); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (90,"HKG","Hong Kong","Hong Kong", 2, 1104); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (91,"HUN","Hungary","Budapest", 3, 93028); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (92,"ISL","Iceland","Reykjavík", 3, 103000); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (93,"IND","India","New Delhi", 2, 3287590); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (94,"IDN","Indonesia","Jakarta", 2, 1904569); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (95,"IRN","Iran","Tehran", 2, 1648195); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (96,"IRQ","Iraq","Baghdad", 2, 438317); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (97,"IRL","Ireland","Dublin", 3, 70273); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (98,"IMN","Isle of Man","Douglas", 3, 572); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (99,"ISR","Israel","Jerusalem", 2, 20770); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (100,"ITA","Italy","Rome", 3, 301336); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (101,"CIV","Ivory Coast","Yamoussoukro", 1, 322463); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (102,"JAM","Jamaica","Kingston", 4, 10991); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (103,"JPN","Japan","Tokyo", 2, 377930); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (104,"JEY","Jersey","Saint Helier", 3, 116); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (105,"JOR","Jordan","Amman", 2, 89342); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (106,"KAZ","Kazakhstan","Nursultan", 2, 2724900); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (107,"KEN","Kenya","Nairobi", 1, 580367); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (108,"KIR","Kiribati","Tarawa", 5, 811); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (109,"KWT","Kuwait","Kuwait City", 2, 17818); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (110,"KGZ","Kyrgyzstan","Bishkek", 2, 199951); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (111,"LAO","Laos","Vientiane", 2, 236800); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (112,"LVA","Latvia","Riga", 3, 64559); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (113,"LBN","Lebanon","Beirut", 2, 10452); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (114,"LSO","Lesotho","Maseru", 1, 30355); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (115,"LBR","Liberia","Monrovia", 1, 111369); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (116,"LBY","Libya","Tripoli", 1, 1759540); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (117,"LIE","Liechtenstein","Vaduz", 3, 160); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (118,"LTU","Lithuania","Vilnius", 3, 65300); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (119,"LUX","Luxembourg","Luxembourg", 3, 2586); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (120,"MAC","Macau","Concelho de Macau", 2, 30); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (121,"MDG","Madagascar","Antananarivo", 1, 587041); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (122,"MWI","Malawi","Lilongwe", 1, 118484); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (123,"MYS","Malaysia","Kuala Lumpur", 2, 330803); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (124,"MDV","Maldives","Malé", 2, 300); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (125,"MLI","Mali","Bamako", 1, 1240192); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (126,"MLT","Malta","Valletta", 3, 316); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (127,"MHL","Marshall Islands","Majuro", 5, 181); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (128,"MTQ","Martinique","Fort-de-France", 4, 1128); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (129,"MRT","Mauritania","Nouakchott", 1, 1030700); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (130,"MUS","Mauritius","Port Louis", 1, 2040); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (131,"MYT","Mayotte","Mamoudzou", 1, 374); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (132,"MEX","Mexico","Mexico City", 4, 1964375); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (133,"FSM","Micronesia","Palikir", 5, 702); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (134,"MDA","Moldova","Chisinau", 3, 33846); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (135,"MCO","Monaco","Monaco", 3, 2); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (136,"MNG","Mongolia","Ulaanbaatar", 2, 1564110); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (137,"MNE","Montenegro","Podgorica", 3, 13812); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (138,"MSR","Montserrat","Brades", 4, 102); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (139,"MAR","Morocco","Rabat", 1, 446550); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (140,"MOZ","Mozambique","Maputo", 1, 801590); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (141,"MMR","Myanmar","Nay Pyi Taw", 2, 676578); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (142,"NAM","Namibia","Windhoek", 1, 825615); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (143,"NRU","Nauru","Yaren", 5, 21); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (144,"NPL","Nepal","Kathmandu", 2, 147181); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (145,"NLD","Netherlands","Amsterdam", 3, 41850); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (146,"NCL","New Caledonia","Nouméa", 5, 18575); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (147,"NZL","New Zealand","Wellington", 5, 270467); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (148,"NIC","Nicaragua","Managua", 4, 130373); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (149,"NER","Niger","Niamey", 1, 1267000); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (150,"NGA","Nigeria","Abuja", 1, 923768); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (151,"NIU","Niue","Alofi", 5, 260); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (152,"PRK","North Korea","Pyongyang", 2, 120538); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (153,"MKD","North Macedonia","Skopje", 3, 25713); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (154,"NFK","Northern Mariana Islands","Saipan", 5, 464); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (155,"NOR","Norway","Oslo", 3, 323802); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (156,"OMN","Oman","Muscat", 2, 309500); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (157,"PAK","Pakistan","Islamabad", 2, 881912); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (158,"PLW","Palau","Ngerulmud", 5, 459); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (159,"PSE","Palestine","Ramallah", 2, 6220); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (160,"PAN","Panama","Panama City", 4, 75417); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (161,"PNG","Papua New Guinea","Port Moresby", 5, 462840); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (162,"PRY","Paraguay","Asunción", 6, 406752); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (163,"PER","Peru","Lima", 6, 1285216); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (164,"PHL","Philippines","Manila", 2, 342353); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (165,"POL","Poland","Warsaw", 3, 312679); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (166,"PRT","Portugal","Lisbon", 3, 92090); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (167,"PRI","Puerto Rico","San Juan", 4, 8870); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (168,"QAT","Qatar","Doha", 2, 11586); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (169,"COG","Republic of the Congo","Brazzaville", 1, 342000); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (170,"REU","Reunion","Saint-Denis", 1, 2511); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (171,"ROU","Romania","Bucharest", 3, 238391); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (172,"RUS","Russia","Moscow", 3, 17098242); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (173,"RWA","Rwanda","Kigali", 1, 26338); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (174,"BLM","Saint Barthelemy","Gustavia", 4, 21); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (175,"KNA","Saint Kitts and Nevis","Basseterre", 4, 261); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (176,"LCA","Saint Lucia","Castries", 4, 616); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (177,"MAF","Saint Martin","Marigot", 4, 53); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (178,"SPM","Saint Pierre and Miquelon","Saint-Pierre", 4, 242); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (179,"VCT","Saint Vincent and the Grenadines","Kingstown", 4, 389); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (180,"WSM","Samoa","Apia", 5, 2842); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (181,"SMR","San Marino","San Marino", 3, 61); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (182,"STP","Sao Tome and Principe","São Tomé", 1, 964); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (183,"SAU","Saudi Arabia","Riyadh", 2, 2149690); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (184,"SEN","Senegal","Dakar", 1, 196722); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (185,"SRB","Serbia","Belgrade", 3, 88361); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (186,"SYC","Seychelles","Victoria", 1, 452); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (187,"SLE","Sierra Leone","Freetown", 1, 71740); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (188,"SGP","Singapore","Singapore", 2, 710); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (189,"SXM","Sint Maarten","Philipsburg", 4, 34); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (190,"SVK","Slovakia","Bratislava", 3, 49037); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (191,"SVN","Slovenia","Ljubljana", 3, 20273); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (192,"SLB","Solomon Islands","Honiara", 5, 28896); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (193,"SOM","Somalia","Mogadishu", 1, 637657); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (194,"ZAF","South Africa","Pretoria", 1, 1221037); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (195,"KOR","South Korea","Seoul", 2, 100210); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (196,"SSD","South Sudan","Juba", 1, 619745); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (197,"ESP","Spain","Madrid", 3, 505992); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (198,"LKA","Sri Lanka","Colombo", 2, 65610); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (199,"SDN","Sudan","Khartoum", 1, 1886068); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (200,"SUR","Suriname","Paramaribo", 6, 163820); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (201,"SWE","Sweden","Stockholm", 3, 450295); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (202,"CHE","Switzerland","Bern", 3, 41284); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (203,"SYR","Syria","Damascus", 2, 185180); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (204,"TWN","Taiwan","Taipei", 2, 36193); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (205,"TJK","Tajikistan","Dushanbe", 2, 143100); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (206,"TZA","Tanzania","Dodoma", 1, 945087); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (207,"THA","Thailand","Bangkok", 2, 513120); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (208,"TLS","Timor-Leste","Dili", 2, 14874); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (209,"TGO","Togo","Lomé", 1, 56785); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (210,"TKL","Tokelau","Nukunonu", 5, 12); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (211,"TON","Tonga","Nuku‘alofa", 5, 747); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (212,"TTO","Trinidad and Tobago","Port-of-Spain", 4, 5130); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (213,"TUN","Tunisia","Tunis", 1, 163610); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (214,"TUR","Turkey","Ankara", 2, 783562); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (215,"TKM","Turkmenistan","Ashgabat", 2, 488100); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (216,"TCA","Turks and Caicos Islands","Cockburn Town", 4, 948); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (217,"TUV","Tuvalu","Funafuti", 5, 26); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (218,"UGA","Uganda","Kampala", 1, 241550); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (219,"UKR","Ukraine","Kiev", 3, 603500); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (220,"ARE","United Arab Emirates","Abu Dhabi", 2, 83600); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (221,"GBR","United Kingdom","London", 3, 242900); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (222,"USA","United States","Washington, D.C.", 4, 9372610); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (223,"VIR","United States Virgin Islands","Charlotte Amalie", 4, 347); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (224,"URY","Uruguay","Montevideo", 6, 181034); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (225,"UZB","Uzbekistan","Tashkent", 2, 447400); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (226,"VUT","Vanuatu","Port-Vila", 5, 12189); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (227,"VAT","Vatican City","Vatican City", 3, 1); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (228,"VEN","Venezuela","Caracas", 6, 916445); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (229,"VNM","Vietnam","Hanoi", 2, 331212); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (230,"WLF","Wallis and Futuna","Mata-Utu", 5, 142); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (231,"ESH","Western Sahara","El Aaiún", 1, 266000); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (232,"YEM","Yemen","Sanaa", 2, 527968); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (233,"ZMB","Zambia","Lusaka", 1, 752612); 
INSERT INTO country (id, cca3, name, capital, continent_id, area_km2) VALUES (234,"ZWE","Zimbabwe","Harare", 1, 390757); 
